#! /bin/bash
echo "115.238.185.30 frp.tcotp.cn" >> /etc/hosts
wget https://cdn.tcotp.cn:4443/client/Sakura_frpc_linux_amd64.tar.gz
tar -xzvf Sakura_frpc_linux_amd64.tar.gz


# 30 洛杉矶 
# 38 新加坡
# 39 蒙特利尔
# 45 美国纽约
chmod +x Sakura_frpc_linux_amd64

echo -e 'ash12358\n12358a\n38' | nohup ./Sakura_frpc_linux_amd64 &
while [[ $? -eq 1 ]]
do
	echo 'open Sakura failed'
	sleep 5s
	echo -e 'ash12358\n12358a\n38' | nohup ./Sakura_frpc_linux_amd64 &
done
echo 'open Sakura success'
